package com.pubnub.api;

public enum OperationType {
    SUBSCRIBE,
    UNSUBSCRIBE,
    PUBLISH,
    HISTORY,
    WHERE_NOW,
    HERE_NOW_GLOBAL,
    HERE_NOW_FOR_CHANNEL,
    HERE_NOW_FOR_CHANNEL_GROUP,
    GRANT,
    REVOKE,
    AUDIT,
    HEARTBEAT,
    SET_STATE,
    STATE_FOR_CHANNEL,
    STATE_FOR_CHANNEL_GROUP,
    ADD_CHANNELS_TO_GROUP,
    REMOVE_CHANNELS_FROM_GROUP,
    CHANNEL_GROUPS,
    REMOVE_GROUP,
    CHANNELS_FOR_GROUP,
    PUSH_NOTIFICATIONS_ENABLED_CHANNELS,
    ADD_PUSH_NOTIFICATIONS_ON_CHANNELS,
    REMOVE_PUSH_NOTIFICATIONS_FROM_CHANNELS,
    REMOVE_ALL_PUSH_NOTIFICATIONS,
    TIME
}
