package com.pubnub.api;

public enum StatusCategory {
	ACCESS_DENIED,
	TIMEOUT,
	NON_JSON_RESPONSE,
	ENCRYPTION_ERROR,
	API_KEY_ERROR,
	CONNECT,
	EXPECTED_DISCONNECT,
	UNEXPECTED_DISCONNECT,
	RECONNECT,
	ACK
}
